store/urls.py
from django.conf.urls import patterns, include, url
from cdbazar.views import ViewWithSubView, SearchView, AjaxDispatcher
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView
from .views import *
from .models import Article, Picture, Item
from django.contrib.auth.decorators import login_required, permission_required
p = permission_required('store.add_item')

urlpatterns = patterns('',
                       url(r'^sell/$',                     p(SellView.as_view())),
                       url(r'^basket/$',                   p(BasketView.as_view())),
                       url(r'^buyout/$',                   p(BuyoutView.as_view())),
                       url(r'^buyout/to-stock/$',          p(BuyoutToStockView.as_view())),
                       url(r'^buyout/to-store/$',          p(BuyoutToStoreView.as_view())),
                       url(r'^buyout/to-clean/$',          p(BuyoutToCleanView.as_view())),
                       url(r'^buyout/lookup/$',            p(BuyoutLookupView.as_view())),
                       url(r'^buyout/load-detail/$',       p(BuyoutLoadDetailView.as_view())),
                       url(r'^item/(?P<pk>\d+)/$',         p(DetailView.as_view(model=Item))),
                       url(r'^item/(?P<pk>\d+)/edit/$',    p(ItemUpdateView.as_view(success_url="/store/item/"))),
                       url(r'^item/(?P<pk>\d+)/to-basket/$', p(ToBasketView.as_view())),
                       url(r'^item/(?P<pk>\d+)/from-basket/$', p(FromBasketView.as_view())),
                       url(r'^item/(?P<pk>\d+)/edit/(?P<field>\w+)/$',    p(ItemFieldUpdateView.as_view())),
                       url(r'^item/$',                     p(ItemList.as_view())),
                       url(r'^article/(?P<pk>\d+)/edit/$', p(ArticleUpdateView.as_view(success_url="/store/article/"))),
                       url(r'^article/(?P<pk>\d+)/load-picture/$', p(ArticlePictureLoadView.as_view())),

                       url(r'^article/(?P<pk>\d+)/$',      p(ArticleDetailView.as_view())),
                       url(r'^article/add/$',              p(ArticleCreateView.as_view())),
                       url(r'^article/$',                  p(ArticleList.as_view())),
                       url(r'^mediatype/add/$',            p(MediaTypeCreateView.as_view(success_url="/store/item/"))),
                       url(r'^picture/(?P<pk>\d+)/$',      p(DetailView.as_view(model=Picture))),
                       url(r'^picture/$',                  p(ListView.as_view(model=Picture, paginate_by=50))),
                       )
                       

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from cdbazar.views import ViewWithSubView, SearchView, AjaxDispatcher
from django.views.generic import TemplateView, ListView, DetailView, FormView, CreateView, UpdateView
from cdbazar import store
import store.views
import store.models

from cdbazar import eshop
import eshop.models
import eshop.views

# from cdbazar.store.views import ArticleList, ArticleUpdateView
# from cdbazar.store.models import Article, Picture
from cdbazar.accounts.views import UserProfileView
from cdbazar.flatpages.views import FlatPageEditView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# def forEshop(forEshop, forAdmin):
#     def handler(request, *args, **kwargs):
#         user = request.user
#         if user.is_authenticated() and user.has_perm('cdbazar.can_buy'):
#             return forAdmin(request, *args, **kwargs)
#         return forEshop(request, *args, **kwargs)
#     return handler

urlpatterns = patterns('',
                       # Examples:
                       url(r'^media/(?P<path>.*)$', 'django.views.static.serve', { 'document_root': settings.MEDIA_ROOT, }),
                       url(r'^accounts/profile', UserProfileView.as_view()),
                       url(r'^accounts/', include('registration.backends.default.urls')),
                       #url(r'^(?P<pk>\d+)/$',      DetailView.as_view(model=store.models.Article)),
                       #url(r'^(?P<pk>\d+)/edit/$', store.views.ArticleUpdateView.as_view(success_url="/store/article/")),
                       url(r'^eshop/', include('cdbazar.eshop.urls')),
                       url(r'^store/', include('cdbazar.store.urls')),

                       
                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       (r'^inplaceeditform/', include('inplaceeditform.urls')),
                       (r'^tinymce/', include('tinymce.urls')),
)

# staticke stranky
urlpatterns += patterns('django.contrib.flatpages.views',
                        url(r'^$',   'flatpage', {'url': '/'}, name='home-page'),
                        url(r'^o-nas/$',   'flatpage', {'url': '/o-nas/'}, name='about'),
                        #url(r'^o-nas/edit$', FlatPageEdit.as_view( url='/o-nas/'),
                        url(r'^licence/$', 'flatpage', {'url': '/licence/'}, name='license'),
                        url(r'^kontakt/$', 'flatpage', {'url': '/kontakt/'}, name='contact'),
)
                        

store/models.py
# -*- coding: utf-8 -*-
from django.db import models, transaction, connection
from django.utils.translation import ugettext_lazy as _, ugettext
from datetime import datetime
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django_extensions.db.models import TimeStampedModel
import re
import os
from cdbazar.settings import MEDIA_ROOT
import urllib
from hashlib import md5
import magic, sh

# Create your models here.

ARTICLE_TYPES = (
    ('CD','CD'),
    ('SA CD','SA CD'),
    ('DVD','DVD'),
    ('DVD audio','DVD audio'),
    ('Playstation 2','Playstation 2'),
    ('Playstation 3','Playstation 3'),
    ('XBox 360','XBox 360'),
    ('PC hry','PC hry'),
    ('Blu-Ray disk','Blu-Ray disk'),
    ('PSP','PSP'),
    )

class MediaType(models.Model):
    name = models.CharField(_("Name"), max_length=16, db_index=True, unique=True)
    desc = models.CharField(_("Description"), max_length=48, blank=True)
    order  = models.SmallIntegerField(u"Pořadí", default=1, blank=True)

    def normalized_key (self):
        return slugify(self.key)

    def __unicode__(self):
        return u"%s" % (self.name,)

# Create your models here.
class Picture(models.Model):
    class Meta:
        verbose_name = _('picture')
        verbose_name_plural = _('Pictures')
        
    img = models.ImageField(upload_to="img/articles", max_length="2048")

    def __unicode__(self):
        return unicode(self.img)

    def delete(self):
        sh.rm("-f",self.img.path)
        super(Picture,self).delete()
        pass
    
    @staticmethod
    def loadFromURL(url):
        """
        http://www.audio3.cz/images/goods_galery/1969818/1969818__1.jpg
        """
        img = urllib.urlopen(url).read()
        imgBaseName = md5(url).hexdigest()
        mime = magic.from_buffer(img, mime=True)
        extension = 'jpeg' in mime and 'jpg' or 'png'
        imgName = os.path.join('img','articles', imgBaseName + "." + extension )
        absImagePath = os.path.join(MEDIA_ROOT, imgName)
        file(absImagePath,'wb').write(img)
        (picture,created) = Picture.objects.get_or_create(img=imgName)
        if created:
            picture.save()
        return picture

    @staticmethod
    def loadFromFile(path):
        imgBaseName = md5(path).hexdigest()
        dirPath= re.search('(..)(..)(..)',imgBaseName).groups()
        relImgPath = "img/articles/" + "/".join(dirPath)
        imgPath= os.path.join(MEDIA_ROOT,relImgPath)
        sh.mkdir("-p",imgPath)
        extension = 'jpeg' in magic.from_file(path, mime=True) and 'jpg' or 'png'
        imgName = imgBaseName + "." + extension
        sh.cp(path, os.path.join(imgPath,imgName))
        (picture, created) = Picture.objects.get_or_create(img=os.path.join(relImgPath,imgName))
        if created:
            picture.save()
        return picture
        
class ForEShopManager(models.Manager):
    def get_queryset(self):
        return super(ForEShopManager, self).get_queryset().filter(eshop=True)

class AtActionManager(models.Manager):
    def get_queryset(self):
        return super(AtActionManager, self).get_queryset().filter(eshop=True)

class Article(models.Model):
    title = models.CharField(_('Title'),max_length=222)
    interpret = models.CharField(_("Interpret"), max_length=64, blank=True, null=True)
    year = models.IntegerField(_("Year"), blank=True, null=True)
    publisher = models.CharField(_('Publisher'),max_length=64, blank=True)
    mediaType = models.ForeignKey(MediaType, blank=True, null=True)
    specification = models.TextField(_("Specification"), blank=True, null=True)
    tracklist = models.TextField(_("Tracklist"), blank=True, null=True)
    origPrice = models.DecimalField(_("Original price"),max_digits=7, decimal_places=2, blank=True, default=0.0)
    barcode = models.CharField(max_length=32, db_index=True, blank=True, null=True)
    pictureSource = models.TextField(u"URL k obrázku", blank=True, null=True)
    picture = models.ForeignKey(Picture, blank=True, null=True)
    slug = models.SlugField(max_length=126,blank=True,null=True) # will be created aftersave
    eshop = models.BooleanField(_("For E-Shop?"), 
                                help_text=_("Has items for sale in an eshop?"), 
                                default=False)
    to_store = models.DateTimeField(_("To store date of an item"), auto_now=True)
    discount = models.BooleanField(_("Has discount?"), 
                                   help_text=_("Has discount?"), 
                                   default=False)
    
    last_modified = models.DateTimeField(_("Last modified"), auto_now=True)

    objects = models.Manager()
    objectsForEShop = ForEShopManager()
    objectsAtAction = AtActionManager()

    def hasItemsForShop(self):
        return self.item_set.all().filter(state__in = (Item.state_at_stock, Item.state_for_sale)).exists()
    
    @classmethod
    def updateEShop(cls):
        cursor = connection.cursor()
        cursor.execute("update store_article set eshop=True where id in (select distinct article_id from store_item where state in (%s,%s))",[Item.state_at_stock, Item.state_for_sale])
        cursor.execute("update store_article set eshop=False where id not in (select distinct article_id from store_item where state in (%s,%s))",[Item.state_at_stock, Item.state_for_sale])

    @classmethod
    def updateDiscount(cls):
        cursor = connection.cursor()
        cursor.execute("update store_article set discount=True where id in (select distinct article_id from store_item where id in (select distinct item_id from eshop_tradeaction))")
        cursor.execute("update store_article set discount=False where id not in (select distinct article_id from store_item where id in (select distinct item_id from eshop_tradeaction))")

            
    def _createSlug(self):
        title = self.title or 'unknown'
        interpret = self.interpret or 'unknown'
        year = self.year or 'someyear'
        slug = slugify(" ".join([aa for aa in (self.title,) if aa]))
        count = 1
        newslug = slug
        while Article.objects.filter(slug=newslug).count():
            newslug = slug + "-%02d" % (count,)
            count += 1
        self.slug=newslug

    def save(self, *args, **kwargs):
        self.slug = self._createSlug()
        super(Article,self).save(*args,**kwargs)

    def __unicode__(self):
        return u"%s (%s)" % (self.title, self.interpret)

    def _last_sold(self):
        return [0.0, None] # cena a datum

    def _for_sale_price_range(self):
        prices = [ ii['price'] for ii in self.item_set.filter(state__in=[Item.state_for_sale,Item.state_at_stock]).values('price')] or [0]
        return (min(prices), max(prices))

    lastSold = property(_last_sold)
    forSalePriceRange = property(_for_sale_price_range)


# class ItemState(models.Model):
#     name = models.CharField(_('Name'),max_length=40, unique=True)
#     desc = models.CharField(_("Description"), max_length=48, blank=True)
#     start = models.BooleanField(_("Start state"), unique=False)

#     @staticmethod
#     def getStart():
#         start = ItemState.objects.filter(start=True)
#         return start.count() and start[0]

#     def __unicode__(self):
#         return u"%s (%s)" % (self.desc, self.name)

# ItemState.state_at_stock = ItemState.objects.get(name='At stock')
# ItemState.state_cleaning = ItemState.objects.get(name='Cleaning')
# ItemState.state_for_sale = ItemState.objects.get(name='For sale')
# ItemState.state_sold = ItemState.objects.get(name='Sold')
# ItemState.state_ordered = ItemState.objects.get(name='Ordered')
# ItemState.state_expedited = ItemState.objects.get(name='Expedited')
    
# models.ForeignKey(ItemState, blank=True, null=True)

#     DATATYPES = ( (1,'basket number'),
#                   (2,'by store'),
#                   (3,'by eshop'),
#                   )

class Item(models.Model):
    STATES = ( (1,'At stock'),
               (2,'Cleaning'),
               (3,'For sale'),
               (4,'Ordered'),
               (5,'Expedited'),
               (6,'Sold'),
               )
    
    article = models.ForeignKey(Article)
    commentary = models.CharField(_('Commentary'), max_length=128, blank=True)
    barcode = models.CharField(_('Barcode'), max_length=128, blank=True, db_index=True)
    packnumber = models.CharField(u"Číslo obálky", max_length=128, blank=True,db_index=True)
    price = models.DecimalField(_('Price'), max_digits=7,decimal_places=2, blank=True, default=0.0)
    state = models.PositiveSmallIntegerField(_("State"), choices=STATES, default=1)
    last_modified = models.DateTimeField(_("Last modified"), auto_now=True)
    to_store = models.DateTimeField(_("To store date"), auto_now=True)
    home_page = models.BooleanField(_("Show at home page"), default=False)

    # def changeState(self,previous_state=None,target_state=None,**kwargs):
    #     ItemAction( item=self, action=ItemAction.STATES['change state'],  **kwargs).save()
    #     self.state = target_state

    # def save(self,*args, **kwargs):
    #     self.state = (self.state is not None and self.state) or Item.state_at_stock
    #     # if self.id:
    #     #     oldState = Item.objects.get(id=self.id).state
    #     #     if self.state != oldState:
    #     #         self.changeState(previous_state=oldState, target_state=self.state)
    #     #     super(Item,self).save(*args,**kwargs)
    #     # else:
    #     #     super(Item,self).save(*args,**kwargs)
    #     #     ItemAction(item=self, action=ItemAction.STATES['init state']).save()
    #     super(Item,self).save(*args,**kwargs)

    def has_tradeaction(self):
        return bool(len(self.tradeaction_set.all()))

    def __unicode__(self):
        result = u"/".join([ii for ii in [ unicode(self.article),unicode(self.barcode)] if ii]) \
                 + " | " \
                 + unicode(self.price) + u" Kč"
        return result

    class Meta:
        verbose_name = _('Item')

templates/store/article_detail.html
{% load i18n thumbnail %}
<div class="article" title='{% trans "article" %}' id="article_detail_{{ article.id }}">
  {% thumbnail article.picture "170x170" as im %}
  <img class="picture" src="/media/{{im.url}}" width="{{ im.width }}" height="{{ im.height }}"></img>
  {% endthumbnail %}
  <span class="tools">
    <a class="edit" href="{{request.path}}{{ article.id }}/edit/">{% trans 'edit' %}</a>
  </span>
  <div class="detail" title='{% trans "detail" %}'>
    <span class="header">{{ article }}</span>
    <table>
      <tbody>
	<tr class="interpret">
	  <th class="label">{% trans "interpret" %}</th>
	  <td class="value">{{ article.interpret }}</td>
	</tr>
	<tr class="title">
	  <th class="label">{% trans "title" %}</th>
	  <td class="value">{{ article.title }}</td>
	</tr>
	<tr class="year">
	  <th class="label">{% trans "year" %}</th>
	  <td class="value">{{ article.year }}</td>
	</tr>
	<tr class="publisher">
	  <th class="label">{% trans "publisher" %}</th>
	  <td class="value">{{ article.publisher }}</td>
	</tr>
	<tr class="media-type">
	  <th class="label">{% trans "media type" %}</th>
	  <td class="value">{{ article.mediaType.name }}</td>
	</tr>
	<tr class="barcode">
	  <th class="label">{% trans "barcode" %}</th>
	  <td class="value">{{ article.barcode }}</td>
	</tr>
	<tr class="packnumber">
	  <th class="label">{% trans "packnumber" %}</th>
	  <td class="value">{{ article.packnumber }}</td>
	</tr>
	<tr class="price">
	  <th class="label">{% trans "price" %}</th>
	  <td class="value">{{ article.price }}</td>
	</tr>
	<tr class="last-sold-price">
	  <th class="label">{% trans "last sold price" %}</th>
	  <td class="value">{{ article.lastSold }}</td>
	</tr>
      </tbody>
    </table>
  </div>
  <table>
    <tbody>
      {% autoescape off %}
      <tr class="specification">
	<th class="label">{% trans "specification" %}</th>
	<td class="value">{{ article.specification }}</td>
      </tr>
      <tr class="tracklist">
	<th class="label">{% trans "tracklist" %}</th>
	<td class="value">{{ article.tracklist }}</td>
      </tr>
      {% endautoescape %}
    </tbody>
  </table>
</div>

templates/store/article_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}{% include "store/item_form/form.html" %}{% endblock %}

templates/store/article_load_picture.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}
{% include "store/article_load_picture/form-header.html" %}
{% include "store/article_load_picture/form-body.html" %}
{% endblock %}

templates/store/basket.html
{% load i18n %}
<script type="text/javascript">
$(function(){  
  {% include "store/basket/js.js" %}
});
</script>
<span class="basket">{% include "store/basket/summary.html" %}</span>

templates/store/basket_review.html
{% extends "base.html" %}
{% load i18n %}
{% block extrastyle %}
<script type="text/javascript">
$(function(){  
  {% include "store/basket_review/js.js" %}
});
</script>
{% endblock %}
{% block title %}{% trans "Basket Review" %}{% endblock %}
{% block left_column %}
{% include "store/mediatype_choose.html" %}
{% endblock %}
{% block content %}
<span class="basket-review">{% include "store/basket_review/list.html" %}</span>
{% endblock %}

templates/store/buyout.html
{% extends "base.html" %}

{% load i18n %}
{% block extrastyle %}
<script type="text/javascript">
$(function(){  
  {% include "store/buyout/js.js" %}
  {% include "store/item_list/js.js" %}
  {% include "store/basket_review/js.js" %}
  //jQuery('#id_buyout-barcode').focus();
});
</script>
{% endblock %}
{% block navigation %}{% include "store/basket.html" %}{% endblock %}
{% block left_column %}
<div class="basket-review">{% include "store/basket_review/list.html" %}</div>
<hr/>
{% endblock %}
{% block title %}{% endblock %}

{% block content %}{% include "store/buyout/form.html" %}{% endblock %}

templates/store/item_field_update.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}
{% include "store/item_field_update/form-header.html" %}
{% include "store/item_field_update/form-body.html" %}
{% endblock %}

templates/store/item_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}
{% include "store/item_form/form_header.html" %}
{% include "store/item_form/form_body.html" %}
{% endblock %}

templates/store/item_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Goods" %}{% endblock %}
{% block extrastyle %}
<script type="text/javascript">
$(function(){
{% include "store/item_list/js.js" %}
{% include "store/basket_review/js.js" %}
});
</script>
{% endblock %}
{% block navigation %}{% include "store/basket.html" %}{% endblock %}
{% block content %}
<div class="item_edit modal hide fade">
  <div class="modal-header">
  </div>
  <div class="modal-body">
  </div>
</div>
<div class="item_list">

<form method="get" action="/store/item/">
<input type="text" class="search-query" placeholder="Hledani" name="search"></input>
</form>

<form class="pagestate" action="" method="post">
  {% csrf_token %}
  {{ pagestate_form }}
</form>

<h2>{% trans "Goods" %}</h2>

<div class="tools"><a class="add btn btn-secondary btn-normal
                             pull-right" href="/store/item/add/">+</a>
</div>
<div class="pagination">{% include "paginator.html" %}</div>
<div class="list">{% include "store/item_list/list.html" %}</div>
<div class="pagination">{% include "paginator.html" %}</div>
</div>
<script type="text/javascript">
jQuery(".item_list form input[name='search']").focus();
</script>
{% endblock %}
{% block left_column %}
<div class="basket-review">{% include "store/basket_review/list.html" %}</div>
<hr/>
{% include "store/mediatype_choose.html" %}
{% endblock %}
{% block right_column %}{% endblock %}

templates/store/mediatype_choose.html
{% load i18n %}
<ul class="nav nav-list">
  <li class="nav-header">{% trans 'Choose media type' %}</li>
  {% for type in mediatypes %}
  <li {% if mediatype == type.name %} class="active" {% endif %}><a href="?mediaType={{ type.name }}">{{ type.desc }}</a></li>
  {% endfor %}
</ul>

templates/store/mediatype_form.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}
{% block content %}{% include "store/mediatype_form/form.html" %}{% endblock %}

templates/store/picture_list.html
{% load i18n %}
<div class="picture_list">
<h2>{% trans "Picture List" %}</h2>
{% for picture in object_list %}
{% include "store/picture_detail.html" %}
{% endfor %}
{% include "paginator.html" %}
</div>

templates/store/sell.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% endblock %}

{% block extrastyle %}
<script type="text/javascript">
$(function(){setTimeout(function(){window.location.replace("/store/item");},1000);});
</script>
{% endblock %}

{% block content %}
<p class="well text-success">{% trans 'The goods are leaving, the money are comming.' %}</p>
{% endblock %}

templates/store/to_basket.html
{% extends "base.html" %}
{% load i18n %}
{% block extrastyle %}
<script type="text/javascript">
$(function(){
{% include "store/to_basket/js.js" %}
});
</script>
{% endblock %}
{% block title %}{% endblock %}
{% block messages %}<div class="messages">{% include "store/to_basket/done.html" %}</div>{% endblock %}
{% block content %}{% endblock %}
{% block left_column %}{% include "store/mediatype_choose.html" %}{% endblock %}
{% block right_column %}{% include "store/basket.html" %}{% endblock %}